language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
before_script:
  - psql -c 'create database redmine_test with encoding=''UTF8'' owner=postgres;' -U postgres    
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test REDMINE_LANG=en bundle exec rake redmine:load_default_data
